name: dta
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - biopython
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - PyTDC
